### ISSUE TITLE
[MacOS]There's sound but black screen

### ISSUE THREAD

**Issue by crazecoder** [media-kit/media-kit#1049]
Tried release mode and debug mode, It's the same whether 
```yaml
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
```
or
```yaml
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: media_kit
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```
It also appears in android's debug mode, but release works fine
