### ISSUE TITLE
On playing back HLS: RangeError (length): Invalid value: Only valid value is 0: 1

### ISSUE THREAD

**Issue by yerzhant** [media-kit/media-kit#1104]
On playing https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8 got this error:
```
I/flutter (11743): RangeError (length): Invalid value: Only valid value is 0: 1
I/flutter (11743): #0      List.[] (dart:core-patch/growable_array.dart)
I/flutter (11743): #1      NativePlayer._handler.<anonymous closure> (package:media_kit/src/player/native/player/real.dart:1749:44)
I/flutter (11743): #2      MapBase.map (dart:collection/maps.dart:82:28)
I/flutter (11743): #3      NativePlayer._handler (package:media_kit/src/player/native/player/real.dart:1746:16)
I/flutter (11743): #4      InitializerNativeEventLoop._receiver.<anonymous closure> (package:media_kit/src/player/native/core/initializer_native_event_loop.dart:140:37)
I/flutter (11743): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1609:10)
I/flutter (11743): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)
I/flutter (11743): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
I/flutter (11743): #8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:777:19)
I/flutter (11743): #9      _StreamController._add (dart:async/stream_controller.dart:651:7)
I/flutter (11743): #10     _StreamController.add (dart:async/stream_controller.dart:606:5)
I/flutter (11743): #11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

main.dart:
```
import 'package:flutter/material.dart';
import 'package:media_kit/media_kit.dart';

void main() {
  MediaKit.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final player = Player();

  @override
  void dispose() async {
    await player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            FilledButton(
              onPressed: () async {
                await player.open(Media(
                  'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
                ));
                // await player.open(Media(
                //   'https://cdn.bitmovin.com/content/assets/art-of-motion-dash-hls-progressive/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa-audio-only.m3u8',
                // ));
              },
              child: Text('Play'),
            ),
            FilledButton(
              onPressed: () async {
                await player.stop();
              },
              child: Text('Stop'),
            ),
          ],
        ),
      ),
    );
  }
}
```

pubspec.yaml:
```
name: mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5

dev_dependencies:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
```

**Comment by Guo8a** [comment]
same question here

**Comment by abdelaziz-mahdy** [comment]
give it a try with the main branch since it may be fixed

```
dependency_overrides:
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```
