### ISSUE TITLE
A ValueNotifier<VideoViewParameters> was used after being disposed.

### ISSUE THREAD

**Issue by ksanchez9306** [media-kit/media-kit#1124]
flutter: FINE: 2025-02-27 14:42:51.681032: socket receive: type "ping", data "null"
flutter: FINE: 2025-02-27 14:42:51.681202: flushing 1 packets in socket
flutter: media_kit: wakelock: _count = 1
flutter: media_kit: wakelock: _count = 2
flutter: VideoOutput.Resize
flutter: {handle: 5623262544, id: 0, rect: {top: 0.0, left: 0.0, height: 1280.0, width: 720.0}}
flutter: media_kit: wakelock: _count = 1

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
A ValueNotifier<VideoViewParameters> was used after being disposed.
Once you have called dispose() on a ValueNotifier<VideoViewParameters>, it can no longer be used.

When the exception was thrown, this was the stack:
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:183:9)
change_notifier.dart:183
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:190:6)
change_notifier.dart:190
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:416:27)
change_notifier.dart:416
#3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:559:5)
change_notifier.dart:559
#4      VideoState.didUpdateWidget.<anonymous closure> (package:media_kit_video/src/video/video_texture.dart:266:38)
video_texture.dart:266
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
binding.dart:1397
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331:11)
binding.dart:1331
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
binding.dart:1176
#11     _invoke (dart:ui/hooks.dart:314:10)
hooks.dart:314
#12     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
platform_dispatcher.dart:419
#13     _drawFrame (dart:ui/hooks.dart:283:31)
hooks.dart:283
(elided 3 frames from dart:async)

i get this error in my app in production when scrolling a pageview.builder that have a list of videos the app try to emulate an infinite scroll like tiktok i receive the videos urls from s3 and this urls already have a transcodification using media converter from aws 

how to solve this error, also i have error in high memory consume using the playlist mode to reproduce the urls from a list
Packages 
Flutter 3.24.3 
media_kit: ^1.1.11
media_kit_libs_video: ^1.0.5
media_kit_video: ^1.2.5

**Comment by abdelaziz-mahdy** [comment]
latest version is from github give it a try
```
dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```
