### ISSUE TITLE
Video only play audio and show black screen

### ISSUE THREAD

**Issue by LostArrows27** [media-kit/media-kit#1125]
I'm using the lastest version of media-kit and try to play video. But the video just show nothing but a black screen, while other function is still working as well
- The audio still play
- The progress bar still work okay too

This is my code and preview of the UI it show. Do you guys have any idea on how to fix this ?

```
import 'package:flutter/material.dart';
import 'package:graduation_thesis_front_end/core/mock/data/fake_video_chunk.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

class VideoViewer extends StatefulWidget {
  final String videoRenderId;

  const VideoViewer({super.key, required this.videoRenderId});

  @override
  State<VideoViewer> createState() => _VideoViewerState();
}

class _VideoViewerState extends State<VideoViewer> {
  late final player = Player();
  late final controller = VideoController(player);

  @override
  void initState() {
    super.initState();
    player.open(Media(
        'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'));
  }

  @override
  void dispose() {
    player.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.width * 9.0 / 16.0,
        child: Video(controller: controller),
      ),
    );
  }
}

```

![Image](https://github.com/user-attachments/assets/cc22fd3d-2ae2-4838-b003-cac124415ed8)

**Comment by abdelaziz-mahdy** [comment]
latest version is from github give it a try

```
dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```

**Comment by LostArrows27** [comment]
@abdelaziz-mahdy  i tried it but it still got black screen :((
This is my pubspecl.yaml
```
name: graduation_thesis_front_end
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0

  fpdart: ^1.1.1
  supabase_flutter: ^2.8.3
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1
  go_router: ^14.8.0
  flex_color_scheme: ^8.1.0
  image_cropper: ^9.0.0
  mask_text_input_formatter: ^2.9.0
  lottie: ^3.3.1
  dotted_border: ^2.1.0
  http: ^1.3.0
  confetti: ^0.8.0
  glass: ^2.0.0+2
  flutter_staggered_grid_view: ^0.7.0
  exif: ^3.3.0
  extended_image: ^9.1.0
  provider: ^6.1.2
  audioplayers: ^6.2.0
  percent_indicator: ^4.2.4
  timeago: ^3.2.2
  # chewie: ^1.10.0
  # video_player: ^2.9.3

  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
```
