### ISSUE TITLE
Black screen showing when playing HLS/m3u8 on some android devices

### ISSUE THREAD

**Issue by nightmarefsm** [media-kit/media-kit#1153]
Black screen shows when playing HLS/m3u8 on some Android devices, including modern ones. I'm using the Impeller engine. The same video works well on most devices, but on some, it only shows black screen with audio. How can I fix it? Should I disable Impeller? It was working well before Impeller existed. Thanks.

**[√] Flutter (Channel stable, 3.29.2, on Microsoft Windows [Version 10.0.27823.1000], locale en-US)**

```yaml
  <meta-data
            android:name="io.flutter.embedding.android.EnableImpeller"
            android:value="true" />

```

```yaml

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      ref: main
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      ref: main
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      ref: main
      path: libs/universal/media_kit_libs_video

```
