### ISSUE TITLE
Issues with volume_controller dependency on macos

### ISSUE THREAD

**Issue by Fluxward** [media-kit/media-kit#1161]
I'm using this project, and it has stopped building on macos due to the volume_controller dependency. I've opened a bug on the volume_controller side: https://github.com/kurenai7968/volume_controller/issues/32

**Comment by Fluxward** [comment]
For now, this version specification in pubspec has unblocked the build on macos:

```yaml
dependencies:
  volume_controller: 3.0.2
  media_kit: 
  media_kit_video: 1.3.0
  media_kit_libs_video:
```
