### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by RA341** [media-kit/media-kit#312]
when building on windows it fails

```
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_audio/windows/CMakeLists.txt:77 (message):
  mpv-dev-x86_64-20230404-git-68b3239.7z integrity check failed.


Exception: Unable to generate build files
```

tried flutter clean and then building again didn't work

**Comment by alexmercerind** [comment]
Hi!

It appears that you're trying to use the audio libraries. It's a mistake on our end, apologies. I'll update you when it's resolved.

**Comment by alexmercerind** [comment]
Hi @RA341,

I hope I understood it right, you're using audio libraries on Windows. I've fixed this & published an update:

Please refer to README for more details.

```yaml
dependencies:
  media_kit: ^1.1.1                              # Primary package.
  
  media_kit_native_event_loop: ^1.0.6            # Support for higher number of concurrent instances & better performance.
  
  media_kit_libs_android_audio: ^1.3.0           # Android package for audio native libraries.
  media_kit_libs_ios_audio: ^1.0.5               # iOS package for audio native libraries.
  media_kit_libs_macos_audio: ^1.0.6             # macOS package for audio native libraries.
  media_kit_libs_windows_audio: ^1.0.5           # Windows package for audio native libraries.
  media_kit_libs_linux: ^1.0.2                   # GNU/Linux dependency package.
```
