### ISSUE TITLE
Failed to load 'media_kit_video' podspec:

### ISSUE THREAD

**Issue by yang282441848** [media-kit/media-kit#322]
Hi there,

Something went wrong when I use media_kit with mac-m1

Can u give me some advise?
### pubspec.yaml
```yaml
name: client
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  media_kit: ^1.1.1
  media_kit_video: ^1.1.1
  media_kit_libs_macos_video: ^1.0.6
  media_kit_libs_macos_audio: ^1.0.6
  mqtt_client: ^10.0.0
  protobuf: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
### console 
```
[   +4 ms] executing: which pod
[  +12 ms] <- compile package:client/main.dart
[  +10 ms] executing: pod --version
[ +295 ms] 1.12.1
[        ] Running pod install...
[ +428 ms] Running pod install... (completed in 424ms)
[        ] CocoaPods' output:
           ↳
[        ]       Preparing

               Analyzing dependencies

               Inspecting targets to integrate
                 Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
                 Using `ARCHS` setting to build architectures of target `Pods-RunnerTests`: (``)

               Finding Podfile changes
                 A media_kit_libs_macos_audio
                 A media_kit_libs_macos_video
                 - FlutterMacOS
                 - media_kit_video
                 - package_info_plus
                 - screen_brightness_macos
                 - wakelock_plus

               Fetching external sources
               -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
               -> Fetching podspec for `media_kit_libs_macos_audio` from `Flutter/ephemeral/.symlinks/plugins/media_kit_libs_macos_audio/macos`
               make: Nothing to be done for `all'.
               -> Fetching podspec for `media_kit_libs_macos_video` from `Flutter/ephemeral/.symlinks/plugins/media_kit_libs_macos_video/macos`
               make: Nothing to be done for `all'.
               -> Fetching podspec for `media_kit_video` from `Flutter/ephemeral/.symlinks/plugins/media_kit_video/macos`
               make: Nothing to be done for `all'.
               media_kit: INFO: package:media_kit_libs_macos_audio found
               media_kit: INFO: package:media_kit_libs_macos_video found
               [!] Failed to load 'media_kit_video' podspec:
               [!] Invalid `media_kit_video.podspec` file: media_kit: ERROR: package:media_kit_libs_macos_*** must be uniq.

                #  from /Users/mason/code/flutter-app/client/macos/Flutter/ephemeral/.symlinks/plugins/media_kit_video/macos/media_kit_video.podspec:13
                #  -------------------------------------------
                #    # Initialize `MediaKitUtils`
                >    mku = MediaKitUtils.new(MediaKitUtils::Platform::MACOS)
                #
                #  -------------------------------------------

               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/external_sources/abstract_external_source.rb:175:in `rescue in store_podspec'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/external_sources/abstract_external_source.rb:161:in `store_podspec'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:997:in `fetch_external_source'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:976:in `block (2 levels) in fetch_external_sources'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:975:in `each'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:975:in `block in fetch_external_sources'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:974:in `fetch_external_sources'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `load'
               /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `<main>'

[        ] Error output from CocoaPods:
           ↳
[        ]     media_kit: ERROR: package:media_kit_libs_macos_*** must be uniq

[+5836 ms] Exception: Error running pod install
[   +1 ms] "flutter run" took 15,148ms.
[   +2 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:757:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


[ +258 ms] ensureAnalyticsSent: 253ms
[        ] Running 1 shutdown hook
[   +8 ms] Shutdown hooks complete
[        ] exiting with code 1
```
