### ISSUE TITLE
Flatpak bundling

### ISSUE THREAD

**Issue by CaptainDario** [media-kit/media-kit#406]
Thanks again for this awesome package!

I am trying to bundle my app using flatpak but I am constantly hitting

``` bash
error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
```

I tried to follow the setup that [the project that is recommended uses](https://github.com/ubuntu-flutter-community/musicpod/blob/main/flatpak/spec.json. The processes compiles a lot of stuff but it seems like it is still missing the necessary library.

Do you have any pointers how to get a flatpak running?

Additionally, it would be really nice to get a list of dependencies or smth that medikit uses in its libmpv build. [mpv compilation](/home/dario/dev/DaKanji/flatpak/DaKanji.tar.xz) lists a lot of optional packages, which of them are necessary?

Thank you very much!

**Comment by CaptainDario** [comment]
When looking at `build-dir/files/lib` there is a `libmpv.so`, a `libmpv.so.2` and a `libmpv.so.2.0.0`.
Am I building the wrong libmpv version?

**Comment by CaptainDario** [comment]
my current building `.json` can be found [here](https://github.com/CaptainDario/DaKanji/blob/dev/flatpak/com.DaAppLab.DaKanji.json)

**Comment by birros** [comment]
> ```bash
> error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
> ```

Check your `LD_LIBRARY_PATH` environment variable so that it points to the directory containing the library.

The name of the library is correct, as `media_kit` supports the following names:
https://github.com/media-kit/media-kit/blob/97c2ab230df819b9ebc98b00b55468100faa50c1/media_kit/lib/src/player/native/core/native_library.dart#L48-L52

**Comment by KRTirtho** [comment]
Hey I am currently shipping Spotube using Flatpak you can follow it's manifest if it helps

```yaml
app-id: com.github.KRTirtho.Spotube
runtime: org.gnome.Platform
runtime-version: '44'
sdk: org.gnome.Sdk
command: spotube
finish-args:
- --socket=fallback-x11
- --socket=wayland
- --socket=pulseaudio #This might be needed
- --share=network
- --share=ipc
- --device=dri
- --filesystem=xdg-download
- --talk-name=org.freedesktop.Notifications
- --talk-name=org.kde.StatusNotifierWatcher
- --talk-name=org.freedesktop.secrets
- --filesystem=xdg-documents
- --filesystem=xdg-run/gvfs #This might be needed
- --filesystem=xdg-run/pipewire-0:ro #This might be needed
- --own-name=org.mpris.MediaPlayer2.spotube
- --system-talk-name=org.freedesktop.NetworkManager
modules:
- shared-modules/libappindicator/libappindicator-gtk3-12.10.json
- shared-modules/libsecret/libsecret.json
- name: libnotify
  buildsystem: meson
  config-opts:
  - -Dtests=false
  - -Dintrospection=disabled
  - -Dgtk_doc=false
  - -Ddocbook_docs=disabled
  sources:
  - type: archive
    url: https://download.gnome.org/sources/libnotify/0.7/libnotify-0.7.8.tar.xz
    sha256: 69209e0b663776a00c7b6c0e560302a8dbf66b2551d55616304f240bba66e18c
- name: jsoncpp
  buildsystem: meson
  config-opts:
  - --default-library=shared
  sources:
  - type: git
    url: https://github.com/open-source-parsers/jsoncpp
    tag: 1.9.5

# These are the required dependencies
- name: libmpv
  cleanup:
  - /include
  - /lib/pkgconfig
  - /share/man
  buildsystem: simple
  build-commands:
  - python3 waf configure --prefix=/app --enable-libmpv-shared --disable-cplayer --disable-build-date
    --disable-alsa
  - python3 waf build
  - python3 waf install
  sources:
  - type: git
    url: https://github.com/mpv-player/mpv.git
    tag: v0.35.1
  - type: file
    url: https://waf.io/waf-2.0.25
    sha256: 21199cd220ccf60434133e1fd2ab8c8e5217c3799199c82722543970dc8e38d5
    dest-filename: waf
  modules:
  - name: libass
    cleanup:
    - /include
    - /lib/*.la
    - /lib/pkgconfig
    config-opts:
    - --disable-static
    sources:
    - type: archive
      url: https://github.com/libass/libass/releases/download/0.17.1/libass-0.17.1.tar.xz
      sha256: f0da0bbfba476c16ae3e1cfd862256d30915911f7abaa1b16ce62ee653192784
    modules:
    - name: fribidi
      cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /lib/*.la
      - /share/man
      buildsystem: meson
      config-opts:
      - --buildtype=release
      - -Ddocs=false
      sources:
      - type: git
        url: https://github.com/fribidi/fribidi.git
        tag: v1.0.13
        commit: b54871c339dabb7434718da3fed2fa63320997e5
  - name: x264
    cleanup:
    - /include
    - /lib/pkgconfig
    - /share/man
    config-opts:
    - --disable-cli
    - --enable-shared
    sources:
    - type: git
      url: https://code.videolan.org/videolan/x264.git
      commit: a8b68ebfaa68621b5ac8907610d3335971839d52
      x-checker-data:
        type: json
        url: https://code.videolan.org/api/v4/projects/536/repository/commits
        commit-query: first( .[].id )
        version-query: first( .[].id )
        timestamp-query: first( .[].committed_date )
  - name: nv-codec-headers
    cleanup:
    - '*'
    no-autogen: true
    make-install-args:
    - PREFIX=/app
    sources:
    - type: git
      url: https://github.com/FFmpeg/nv-codec-headers.git
      commit: 855f8263d97bbdcaeabaaaa2997e1ccad7c52dc3
  - name: ffmpeg
    cleanup:
    - /include
    - /lib/pkgconfig
    - /share/ffmpeg/examples
    config-opts:
    - --enable-shared
    - --disable-static
    - --enable-gnutls
    - --disable-doc
    - --disable-programs
    - --disable-encoders
    - --disable-muxers
    - --enable-encoder=png
    - --enable-libv4l2
    - --enable-libdav1d
    sources:
    - type: git
      url: https://git.ffmpeg.org/ffmpeg.git
      branch: release/6.0
      commit: 3d5edb89e75fe3ab3a6757208ef121fa2b0f54c7
# -----------------------------------------------------------------------------------

- name: spotube
  buildsystem: simple
  build-commands:
  - install -Dm644 spotube/com.github.KRTirtho.Spotube.appdata.xml /app/share/appdata/com.github.KRTirtho.Spotube.appdata.xml
  - desktop-file-edit spotube/spotube.desktop --set-key=Exec --set-value="spotube
    %u" --set-icon=com.github.KRTirtho.Spotube
  - install -Dm644 spotube/spotube-logo.png /app/share/icons/hicolor/128x128/apps/com.github.KRTirtho.Spotube.png
  - install -Dm644 spotube/spotube.desktop /app/share/applications/com.github.KRTirtho.Spotube.desktop
  - install -dm755 /app/bin /app/spotube
  - cp -R spotube/ /app
  - ln -s /app/spotube/spotube /app/bin/spotube
  sources:
  - type: archive
    dest: spotube
    url: https://github.com/KRTirtho/spotube/releases/download/v3.1.0/spotube-linux-3.1.0-x86_64.tar.xz
    sha256: d9b38e7b57b04c17822541d122292c461a8db824f1bd10bdc82c23840593f30b
```

**Comment by alexmercerind** [comment]
I consider this as solved. Closing.

The discussion is left open in-case any further conversation is required.

Thanks!

**Comment by CaptainDario** [comment]
@KRTirtho I tried copying your file and adapting it to my file structure. But I am still hitting
`error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`

I build the flatpak like this
``` bash
# building flutter app 
flutter build linux --release
# zip and copy the application to the flatpak directory
...
# build flatpak
flatpak-builder --force-clean build-dir com.DaAppLab.DaKanji.yaml --repo=repo
flatpak build-bundle repo com.DaAppLab.DaKanji.flatpak com.DaAppLab.DaKanji
# install flatpak
flatpak install com.DaAppLab.DaKanji.flatpak
```

The app installs just fine and the icon also shows up in my applications. However, during runtime I encounter the mentioned issue.
Do you have any idea what I am missing? My build `.yaml`:

``` yaml
app-id: com.DaAppLab.DaKanji
runtime: org.gnome.Platform
runtime-version: '44'
sdk: org.gnome.Sdk
command: DaKanji
finish-args:
- --socket=fallback-x11
- --socket=wayland
- --socket=pulseaudio #This might be needed
- --share=network
- --share=ipc
- --device=dri
- --filesystem=xdg-download
- --talk-name=org.freedesktop.Notifications
- --talk-name=org.kde.StatusNotifierWatcher
- --talk-name=org.freedesktop.secrets
- --filesystem=xdg-documents
- --filesystem=xdg-run/gvfs #This might be needed
- --filesystem=xdg-run/pipewire-0:ro #This might be needed
- --own-name=org.mpris.MediaPlayer2.spotube
- --system-talk-name=org.freedesktop.NetworkManager
modules:

# These are the required dependencies
- name: libmpv
  cleanup:
  - /include
  - /lib/pkgconfig
  - /share/man
  buildsystem: simple
  build-commands:
  - python3 waf configure --prefix=/app --enable-libmpv-shared --disable-cplayer --disable-build-date
    --disable-alsa
  - python3 waf build
  - python3 waf install
  sources:
  - type: git
    url: https://github.com/mpv-player/mpv.git
    tag: v0.35.1
  - type: file
    url: https://waf.io/waf-2.0.25
    sha256: 21199cd220ccf60434133e1fd2ab8c8e5217c3799199c82722543970dc8e38d5
    dest-filename: waf
  modules:
  - name: libass
    cleanup:
    - /include
    - /lib/*.la
    - /lib/pkgconfig
    config-opts:
    - --disable-static
    sources:
    - type: archive
      url: https://github.com/libass/libass/releases/download/0.17.1/libass-0.17.1.tar.xz
      sha256: f0da0bbfba476c16ae3e1cfd862256d30915911f7abaa1b16ce62ee653192784
    modules:
    - name: fribidi
      cleanup:
      - /bin
      - /include
      - /lib/pkgconfig
      - /lib/*.la
      - /share/man
      buildsystem: meson
      config-opts:
      - --buildtype=release
      - -Ddocs=false
      sources:
      - type: git
        url: https://github.com/fribidi/fribidi.git
        tag: v1.0.13
        commit: b54871c339dabb7434718da3fed2fa63320997e5
  - name: x264
    cleanup:
    - /include
    - /lib/pkgconfig
    - /share/man
    config-opts:
    - --disable-cli
    - --enable-shared
    sources:
    - type: git
      url: https://code.videolan.org/videolan/x264.git
      commit: a8b68ebfaa68621b5ac8907610d3335971839d52
      x-checker-data:
        type: json
        url: https://code.videolan.org/api/v4/projects/536/repository/commits
        commit-query: first( .[].id )
        version-query: first( .[].id )
        timestamp-query: first( .[].committed_date )
  - name: nv-codec-headers
    cleanup:
    - '*'
    no-autogen: true
    make-install-args:
    - PREFIX=/app
    sources:
    - type: git
      url: https://github.com/FFmpeg/nv-codec-headers.git
      commit: 855f8263d97bbdcaeabaaaa2997e1ccad7c52dc3
  - name: ffmpeg
    cleanup:
    - /include
    - /lib/pkgconfig
    - /share/ffmpeg/examples
    config-opts:
    - --enable-shared
    - --disable-static
    - --enable-gnutls
    - --disable-doc
    - --disable-programs
    - --disable-encoders
    - --disable-muxers
    - --enable-encoder=png
    - --enable-libv4l2
    - --enable-libdav1d
    sources:
    - type: git
      url: https://git.ffmpeg.org/ffmpeg.git
      branch: release/6.0
      commit: 3d5edb89e75fe3ab3a6757208ef121fa2b0f54c7
# -----------------------------------------------------------------------------------

- name: DaKanji
  buildsystem: simple
  build-commands:
  - pwd
  - ls DaKanji -la
  - install -Dm644 DaKanji/com.DaAppLab.DaKanji.appdata.xml /app/share/appdata/com.DaAppLab.DaKanji.appdata.xml
  #- desktop-file-edit DaKanji/DaKanji.desktop --set-key=Exec --set-value="dakanji %u" --set-icon=com.DaAppLab.DaKanji
  - install -Dm644 DaKanji/LaunchImage@2x.png /app/share/icons/hicolor/512x512/apps/com.DaAppLab.DaKanji.png
  - install -Dm644 DaKanji/DaKanji.desktop /app/share/applications/com.DaAppLab.DaKanji.desktop
  - install -dm755 /app/bin /app/DaKanji
  - cp -R DaKanji/ /app
  - ln -s /app/DaKanji/DaKanji /app/bin/DaKanji
  sources:
  - type: archive
    path: bundle.zip
    dest: DaKanji
  - type: file
    path: com.DaAppLab.DaKanji.appdata.xml
    dest: DaKanji
  - type: file
    path: DaKanji.desktop
    dest: DaKanji
  - type: file
    path: ../ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    dest: DaKanji
```
