### ISSUE TITLE
[Bug Report][Android] library "libavcodec.so" not found

### ISSUE THREAD

**Issue by mysCod3r** [media-kit/media-kit#514]
Device:
Samsung A7-2017
Android 8.0

dependencies:
```yaml
  media_kit: ^1.1.8
  media_kit_video: ^1.2.1
  media_kit_native_event_loop: ^1.0.8
  media_kit_libs_android_video: ^1.3.5
  media_kit_libs_ios_video: ^1.1.4
```
```dart
WidgetsFlutterBinding.ensureInitialized();
MediaKit.ensureInitialized(); // error
```

error is:
ArgumentError (Invalid argument(s): Failed to load dynamic library 'libavcodec.so': dlopen failed: library "libavcodec.so" not found)

i tried adding 
```
packagingOptions {
                pickFirst 'lib/arm64-v8a/libavcodec.so'
                pickFirst 'lib/arm64-v8a/libavformat.so'
                pickFirst 'lib/arm64-v8a/libavutil.so'
                pickFirst 'lib/arm64-v8a/libswscale.so'
                pickFirst 'lib/x86/libavcodec.so'
                pickFirst 'lib/x86/libavformat.so'
                pickFirst 'lib/x86/libavutil.so'
                pickFirst 'lib/x86/libswscale.so'
                pickFirst 'lib/x86_64/libavcodec.so'
                pickFirst 'lib/x86_64/libavformat.so'
                pickFirst 'lib/x86_64/libavutil.so'
                pickFirst 'lib/x86_64/libswscale.so'
            }
``` 
into build.gradle.
and i tried 
```dart
MediaKit.ensureInitialized(libmpv: '/app/lib/libmpv.so.2'); 
```

but neither of them solved the issue.
