### ISSUE TITLE
[Bug Report] When seeking an MKV format video on iOS, the error "Seek failed" occurs.

### ISSUE THREAD

**Issue by wangdongmeng** [media-kit/media-kit#527]
plugin version：

```yaml
media_kit: ^1.1.8                              
media_kit_video: ^1.2.1                      
media_kit_libs_video: ^1.0.3   
```

[MacOS,IOS]

When playing MKV videos (1080P or 2160P) on iOS, there is a high probability of encountering the error "Seek failed" when trying to seek. It keeps buffering for about 20 seconds or even longer before starting playback, and sometimes it gets stuck and doesn't play at all. This issue does not occur with MP4 videos. Could you please explain what might be causing this? Thank you!

log：
```
flutter: player.stream.log :PlayerLog(prefix: ffmpeg, level: error, text: Seek failed (to 40667615782, size -78))
flutter: player.stream.log :PlayerLog(prefix: mkv, level: error, text: Corrupt file detected. Trying to resync starting from position 36933742398...)
flutter: player.stream.log :PlayerLog(prefix: mkv, level: error, text: Cluster found at 36933766797.)
```
