### ISSUE TITLE
Way to use main branch in my project?

### ISSUE THREAD

**Issue by Velosofy** [media-kit/media-kit#597]
Is there a way to use the main branch for my project?

I wan't to use the new native command for MPV, so I can add button that set af filters.

**Comment by Velosofy** [comment]
Ah found it, `dependency_overrides`. Whoops

**Comment by birros** [comment]
For the record:
```yaml
dependencies:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./libs/universal/media_kit_libs_video
```
