### ISSUE TITLE
[Video Player Window Media Kit]: Playing Video URL but it got looping

### ISSUE THREAD

**Issue by moshOntong-IT** [media-kit/media-kit#606]
``` yaml
video_player_media_kit 1.0.5
media_kit_libs_android_video: ^1.3.6
media_kit_libs_windows_video: ^1.0.9
```

``` dart
  VideoPlayerMediaKit.ensureInitialized(
    android: true,
    windows: true,
  );
```

Result:

https://github.com/media-kit/media-kit/assets/57244338/7c8b2130-c19f-4211-8655-79c03c289719

As you can see above, the video player source is from the url. Now when I play the video, it loops and dont have audio
