### ISSUE TITLE
Video Player HDR Problem

### ISSUE THREAD

**Issue by vanvixi** [media-kit/media-kit#615]
The problem appears both on android and ios

<table>
    <tr>
         <th style="text-align: center">Native Player</th>
         <th style="text-align: center">media_kit </th>
    </tr>
    <tr>
    <td> <img src="https://github.com/flutter/flutter/assets/75975945/1e145f12-2752-40c1-8859-49e6be76699a"  alt="1" width = 360px height = 640px ></td>
    <td><img src="https://github.com/flutter/flutter/assets/75975945/b9763331-8bb9-4baa-87f9-09baeffa735e" alt="2" width = 360px height = 640px></td>
    </tr> 
</table>

**Comment by sudhanshugairola** [comment]
I also said same thing but they declined that is flutter view issue

**Comment by 23doors** [comment]
@sudhanshugairola no one said it was a flutter view issue. You insisted that platform views will magically fix it. Which is completely untrue. And in your case you used DV content, which is completely unrelated to what's happening here. So please stop spreading misinformation.

@vanvixi media_kit uses mpv and flutter textures. Flutter textures don't have HDR capability on any platform. So HDR needs to be tone mapped to SDR. Which different players handle differently (as there are multiple algorithms for that). Feel free to tinker with https://mpv.io/manual/master/#options-tone-mapping to get better results. 

But point remains, actual HDR passthrough (to leverage actual HDR displays and use high nits values) is currently not possible with flutter textures at all (at least on iOS, Android and Mac, dunno about Windows situation). And on Android, even native MPV Android project doesn't support HDR passthrough.

**Comment by alexmercerind** [comment]
The --tone-mapping property can yield substantial difference in overall HDR rendering:

![](https://media.discordapp.net/attachments/1079815139387252797/1105512567717232690/screenshot_hdr_macos.png?ex=656f3dcf&is=655cc8cf&hm=1503a09d5b3baec97d0183b33cc5ce013c0dd5a303e43e271a8de95630764f86&=&format=webp)

Refer to https://github.com/media-kit/media-kit/issues/14#issuecomment-1373205132 for using custom libmpv options/properties. Project is open to feedback. I believe overall results should be convincing with right configuration.

<hr>

The Dolby Vision HDR is entirely different issue.

**Comment by alexmercerind** [comment]
@sudhanshugairola 

> You insisted that platform views will magically fix it.

In case of ExoPlayer etc. where native HDR support is present, it might be possible that rendering becomes correct with platform views. However, I think even platform-views are off-screen rendered (in-fact not even GPU accelerated on some Android versions/devices) with user interactions handled programmatically (it's not like a punch-hole in Flutter view, let's say).

**Comment by benmccann** [comment]
> In case of ExoPlayer etc. where native HDR support is present, it might be possible that rendering becomes correct with platform views.

See https://github.com/media-kit/media-kit/issues/410 for ExoPlayer support

**Comment by alexmercerind** [comment]
Official package:video_player (though ExoPlayer) also suffers from problems in HDR rendering. Few projects have preferred package:media_kit's HDR rendering (customizable tone-mapping).

**Comment by alexmercerind** [comment]
gpu-next can probably be used on main branch now.

**Comment by vanvixi** [comment]
@alexmercerind 
I just cloned the repository and tried again with your example project (media-kit/video_player_media_kit/example).
It seems things are worse than before.

**Comment by SmartVive** [comment]
> gpu-next can probably be used on main branch now.

@alexmercerind 
how to enable gpu-next? vo=gpu-next not working;

**Comment by SmartVive** [comment]
@alexmercerind 
When I enabled and updated libpacebo it worked. thk!

**Comment by alexmercerind** [comment]
Awesome news. I'll have it in the next version.

**Comment by vanvixi** [comment]
> Awesome news. I'll have it in the next version.

gpu-next is also available for video_player media_kit right?

**Comment by alexmercerind** [comment]
These implementation details are unfortunately hidden from that API surface.

**Comment by LeeeYudE** [comment]
@alexmercerind 
You can tell me that -vo=gpu-next & --hwdec=auto. How to use it.
 I try to use 
VideoControllerConfiguration (enableHardwareAcceleration: true,
vo: 'gpu-next',
hwdec: 'auto',
), but the screen is black, only sound

**Comment by LeeeYudE** [comment]
@alexmercerind 
You can tell me that -vo=gpu-next & --hwdec=auto. How to use it.
I try to use
VideoControllerConfiguration (enableHardwareAcceleration: true,
vo: 'gpu-next',
hwdec: 'auto',
), but the screen is black, only sound

**Comment by LeeeYudE** [comment]
@SmartVive Can you tell me how to enable libpacebo library, I want to play HDR video

**Comment by SmartVive** [comment]
> [@SmartVive](https://github.com/SmartVive) Can you tell me how to enable libpacebo library, I want to play HDR video

fork `https://github.com/media-kit/libmpv-android-video-build` and modify

**Comment by LeeeYudE** [comment]
@SmartVive 
Is it convenient for you to share the compiled full-jar with me? After I fork https://github.com/media-kit/libmpv-android-video-build, an error occurs when I execute the bundle_full.sh script.
```
cp: ../../prefix/arm64-v8a/usr/local/lib: No such file or directory
cp: ../../prefix/x86/usr/local/lib: No such file or directory
cp: ../../prefix/x86_64/usr/local/lib: No such file or directory
libmpv-android-video-build/buildscripts/bundle_full.sh:40: no matches found: prefix/arm64-v8a/usr/local/lib/*.so
libmpv-android-video-build/buildscripts/bundle_full.sh:41: no matches found: prefix/armeabi-v7a/usr/local/lib/*.so
libmpv-android-video-build/buildscripts/bundle_full.sh:42: no matches found: prefix/x86/usr/local/lib/*.so
demo/libmpv-android-video-build/buildscripts/bundle_full.sh:43: no matches found: prefix/x86_64/usr/local/lib/*.so
demo/libmpv-android-video-build/buildscripts/bundle_full.sh:45: no matches found: *.jar
```

By the way, is it possible to open the api for gpu-next
` ` `
VideoController(
player,
configuration: VideoControllerConfiguration(enableHardwareAcceleration: true,
vo: 'gpu-next',
hwdec: 'auto',
),
)
` ` `

**Comment by SmartVive** [comment]
> [@SmartVive](https://github.com/SmartVive) Is it convenient for you to share the compiled full-jar with me? After I fork https://github.com/media-kit/libmpv-android-video-build, an error occurs when I execute the bundle_full.sh script.
> 
> ```
> cp: ../../prefix/arm64-v8a/usr/local/lib: No such file or directory
> cp: ../../prefix/x86/usr/local/lib: No such file or directory
> cp: ../../prefix/x86_64/usr/local/lib: No such file or directory
> libmpv-android-video-build/buildscripts/bundle_full.sh:40: no matches found: prefix/arm64-v8a/usr/local/lib/*.so
> libmpv-android-video-build/buildscripts/bundle_full.sh:41: no matches found: prefix/armeabi-v7a/usr/local/lib/*.so
> libmpv-android-video-build/buildscripts/bundle_full.sh:42: no matches found: prefix/x86/usr/local/lib/*.so
> demo/libmpv-android-video-build/buildscripts/bundle_full.sh:43: no matches found: prefix/x86_64/usr/local/lib/*.so
> demo/libmpv-android-video-build/buildscripts/bundle_full.sh:45: no matches found: *.jar
> ```
> 
> By the way, is it possible to open the api for gpu-next ` ` `VideoController( player, configuration: VideoControllerConfiguration(enableHardwareAcceleration: true, vo: 'gpu-next', hwdec: 'auto', ), )` ` `

`https://github.com/SmartVive/libmpv-android-video-build/releases`

**Comment by LeeeYudE** [comment]
@SmartVive 
I'm sorry to continue to ask you, I'm from https://github.com/SmartVive/libmpv-android-video-build/releases to download the jar into the project, using the configuration broadcast video below

` ` `
VideoController(
player,
configuration: VideoControllerConfiguration(
enableHardwareAcceleration: true,
vo: 'gpu-next',
hwdec: 'auto',
),
)
` ` `

The video playback is stuck, and the exception log is always output. Do you have the option to enable additional configuration to open gpu-next

```
  onSurfaceCreated
I/VideoOutput( 5297): newGlobalRef: object = Surface(name=android.graphics.SurfaceTexture@a7abe)/@0x2d0571f
I/flutter ( 5297): VideoOutput.Resize
I/flutter ( 5297): {rect: {top: 0, left: 0, width: 3840, height: 2160}, wid: 11642, handle: 513821324880, id: 0}
D/AudioTrack( 5297): start: not BaiduNav 
D/SurfaceUtils( 5297): disconnecting from surface 0x77a23a1010, reason disconnectFromSurface
W/MediaAnalyticsItem( 5297): Unable to record: (codec:0:-1:-11:0:8:android.media.mediacodec.codec=OMX.qcom.video.decoder.hevc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:android.media.mediacodec.width=3840:android.media.mediacodec.height=2160:android.media.mediacodec.rotation-degrees=0:android.media.mediacodec.mime=video/hevc:android.media.mediacodec.bytesin=505125:) [forcenew=0]
```

**Comment by SmartVive** [comment]
> [@SmartVive](https://github.com/SmartVive) I'm sorry to continue to ask you, I'm from https://github.com/SmartVive/libmpv-android-video-build/releases to download the jar into the project, using the configuration broadcast video below
> 
> ` ` `VideoController( player, configuration: VideoControllerConfiguration( enableHardwareAcceleration: true, vo: 'gpu-next', hwdec: 'auto', ), )` ` `
> 
> The video playback is stuck, and the exception log is always output. Do you have the option to enable additional configuration to open gpu-next
> 
> ```
>   onSurfaceCreated
> I/VideoOutput( 5297): newGlobalRef: object = Surface(name=android.graphics.SurfaceTexture@a7abe)/@0x2d0571f
> I/flutter ( 5297): VideoOutput.Resize
> I/flutter ( 5297): {rect: {top: 0, left: 0, width: 3840, height: 2160}, wid: 11642, handle: 513821324880, id: 0}
> D/AudioTrack( 5297): start: not BaiduNav 
> D/SurfaceUtils( 5297): disconnecting from surface 0x77a23a1010, reason disconnectFromSurface
> W/MediaAnalyticsItem( 5297): Unable to record: (codec:0:-1:-11:0:8:android.media.mediacodec.codec=OMX.qcom.video.decoder.hevc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:android.media.mediacodec.width=3840:android.media.mediacodec.height=2160:android.media.mediacodec.rotation-degrees=0:android.media.mediacodec.mime=video/hevc:android.media.mediacodec.bytesin=505125:) [forcenew=0]
> ```

Make sure you actually use the new jar. need modify `https://github.com/media-kit/media-kit/blob/4d8c634c28d439384aab40b9d2edff83077f37c9/libs/android/media_kit_libs_android_video/android/build.gradle#L61`

**Comment by maRci002** [comment]
I've been following the discussions about the HDR problem with the video player and noticed that there have been significant updates in Android PR flutter/packages#8237 and iOS PR flutter/packages#8237. Can anyone confirm if these updates have resolved the HDR issue?

Note: _Since the app-facing package still does not support `viewType`, it's a bit challenging to test. However `video_player_platform_interface` already supports [`VideoViewType`](https://github.com/flutter/packages/pull/8453/files#diff-6480bcec21eff8c085e1b1b3fbd5ca69e76212a9843ca76a3dd3ab861f81eef9R528), it's not difficult to fork the repository and make `platformView` the default renderer._

**Comment by Predidit** [comment]
I've made some progress on this issue, referring to flutter/package#8466 . In my [branch](https://github.com/Predidit/media-kit/tree/android-platformview), I've created a proof of concept that migrates the Android implementation from Texture to PlatformView. I'm not sure if I've missed something, but HDR still doesn't seem to be enabled. Interested parties can try out this branch - it at least resolves the issue where Texture components don't support HDR at all. I'm not ready to submit a PR yet, as this implementation is still quite rough and has several outstanding issues.

```
dependencies:
  media_kit:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: android-platformview
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: android-platformview
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: android-platformview
      path: ./libs/universal/media_kit_libs_video

dependency_overrides:
  media_kit_libs_linux:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: android-platformview
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: android-platformview
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: android-platformview
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: android-platformview
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: android-platformview
      path: ./libs/macos/media_kit_libs_macos_video
```
