### ISSUE TITLE
Linux build Failed 

### ISSUE THREAD

**Issue by mathankumar-dotworld** [media-kit/media-kit#695]
Getting this error when trying to build linux
```
/usr/lib/x86_64-linux-gnu/libgdk-3.so  /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so
/usr/lib/x86_64-linux-gnu/libpango-1.0.so  /usr/lib/x86_64-linux-gnu/libharfbuzz.so
/usr/lib/x86_64-linux-gnu/libatk-1.0.so  /usr/lib/x86_64-linux-gnu/libcairo-gobject.so
/usr/lib/x86_64-linux-gnu/libcairo.so  /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so
/usr/lib/x86_64-linux-gnu/libgio-2.0.so  /usr/lib/x86_64-linux-gnu/libgobject-2.0.so
/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[        ] /usr/bin/ld: /lib/x86_64-linux-gnu/libmpv.so.1: undefined reference to `vkCreateWaylandSurfaceKHR'
[        ] /usr/bin/ld: /lib/x86_64-linux-gnu/libmpv.so.1: undefined reference to `vkCreateXlibSurfaceKHR'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[        ] ninja: build stopped: subcommand failed.
[   +6 ms] Building Linux application... (completed in 41.8s)
[        ] "flutter linux" took 42,376ms.
[   +2 ms] Build process failed
```
Flutter version
```
Flutter 3.16.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 41456452f2 (7 days ago) • 2024-01-25 10:06:23 -0800
Engine • revision f40e976bed
Tools • Dart 3.2.6 • DevTools 2.28.5
```
my pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  flutter_linux_webview: ^0.1.2
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4
```
