### ISSUE TITLE
Impeller Engine Support

### ISSUE THREAD

**Issue by fsmdeveloper** [media-kit/media-kit#976]
Has the impeller engine been implemented in the current version?

**Comment by alexmercerind** [comment]
Added on main branch.

**Comment by alexmercerind** [comment]
> Is it stable on media-kit? Is it production-ready, or should I wait?

It's not fully stable yet. Rest... Judge for yourself, the license of this software specifies no warranty.

**Comment by fsmdeveloper** [comment]
@alexmercerind bro, is is now stable? i mean Impeller on media_kit ?

**Comment by abdelaziz-mahdy** [comment]
> @alexmercerind bro, is it now stable? i mean Impeller on media_kit ?

yes on main branch

**Comment by fsmdeveloper** [comment]
How to use main branch in flutter?

is it correct way to use main branch?


dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit
      ref: main
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit
      ref: main
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit
      ref: main
      path: libs/universal/media_kit_libs_video

**Comment by abdelaziz-mahdy** [comment]
yes its correct, and since the indentation looks incorrect this is it with the correct indentation
```
dependency_overrides:
  media_kit: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit
  media_kit_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: media_kit_video
  media_kit_libs_video: 
    git:
      url: https://github.com/media-kit/media-kit
      path: libs/universal/media_kit_libs_video
```
